# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               脑残vBaiCai的备忘录
tagline:             '呆若木鸡，大辩不言'
description:         ''
url:                 http://zhuroubaicai.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              vBaiCai
  url:               https://www.zhihu.com/people/Radon86
  email:             radon86@live.cn

# Custom vars
version:             1.0.0
