# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               脑残vBaiCai的备忘录
tagline:             '呆若木鸡，大辩不言'
description:         '呆若木鸡'
url:                 'http://zhuroubaicai.github.io/'
baseurl:             'http://zhuroubaicai.github.io/'
#Test 
#url:                ''
#baseurl:            ''
paginate:            5

# About/contact
author:
  name:              vBaiCai
  url:               https://www.zhihu.com/people/Radon86
  email:             radon86@live.cn

# Custom vars
version:             1.0.0

highlight:            true

##markdown setting
markdown: kramdown

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
#  coderay:
#   coderay_line_numbers:  nil


  highlighter:          pygments
# markdown:             redcarpet
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - no_intra_emphasis
#     - strikethrough
#     - autolink
#     - tables

# Gems
gems: [jekyll-paginate]