# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               vBaiCai的废旧记忆回收站
tagline:             '呆若木鸡,大辩不言'
description:         '呆若木鸡,怕响晨钟,饱食遨游,一事无成'
url:                 'https://vbaicai.github.io'
baseurl:             'https://vbaicai.github.io'
#Test Config
# url:                ''
# baseurl:            ''
paginate:            5

# About/contact
author:
  name:              vBaiCai
  url:               https://www.zhihu.com/people/Radon86
  email:             radon86@live.cn

# Custom vars
version:             1.0.0

highlight:            true

##markdown setting
markdown: kramdown

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
#  coderay:
#   coderay_line_numbers:  nil


  highlighter:          pygments
# markdown:             redcarpet
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - no_intra_emphasis
#     - strikethrough
#     - autolink
#     - tables

# Gems
gems: [jekyll-paginate]